# -*- coding: utf-8 -*-
"""Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LL97UiWRucjxtlQJjpVMS1ZzDkrUfY8k
"""


# ╔══════════════════════════════════════════════════════════════╗
#  🤖 AI-Based Product Recommendation & Analytics System
#  Google Colab Notebook  |  Major Project
#  Dataset: Product_Recommendation_Dataset.xlsx (3 sheets)
#  Techniques: Content-Based + Collaborative Filtering + SVD
# ╚══════════════════════════════════════════════════════════════╝

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 1 — Install all dependencies
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
!pip install streamlit pyngrok scikit-learn openpyxl scipy --quiet

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 2 — Imports
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from scipy.sparse import csr_matrix
from google.colab import files
import warnings
warnings.filterwarnings("ignore")

plt.rcParams.update({
    "figure.facecolor": "#f8f9fa",
    "axes.facecolor":   "#ffffff",
    "axes.edgecolor":   "#cccccc",
    "axes.spines.top":  False,
    "axes.spines.right": False,
    "font.family":      "DejaVu Sans",
    "axes.titlesize":   14,
    "axes.titleweight": "bold",
})
P = ["#5e60ce","#48cae4","#f72585","#06d6a0","#ffd166",
     "#ef476f","#3a86ff","#fb8500","#8ecae6","#95d5b2"]

print("✅  All libraries imported successfully!")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 3 — Upload & Load all 3 sheets
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
uploaded = files.upload()
FILE = list(uploaded.keys())[0]

users    = pd.read_excel(FILE, sheet_name="Users",        parse_dates=["Join_Date"])
products = pd.read_excel(FILE, sheet_name="Products",     parse_dates=["Launch_Date"])
interact = pd.read_excel(FILE, sheet_name="Interactions", parse_dates=["Date"])

print(f"\n{'━'*55}")
print("  DATASET LOADED")
print(f"{'━'*55}")
print(f"  👤 Users        : {users.shape[0]:,} rows × {users.shape[1]} cols")
print(f"  📦 Products     : {products.shape[0]:,} rows × {products.shape[1]} cols")
print(f"  🔁 Interactions : {interact.shape[0]:,} rows × {interact.shape[1]} cols")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 4 — STEP 1: Null Value Check
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
print(f"\n{'━'*55}")
print("  STEP 1 — NULL VALUE CHECK (ALL 3 SHEETS)")
print(f"{'━'*55}")

for name, df in [("Users", users), ("Products", products), ("Interactions", interact)]:
    nulls = df.isnull().sum()
    null_pct = (nulls / len(df) * 100).round(2)
    null_df = pd.DataFrame({"Count": nulls, "%": null_pct})[nulls > 0]
    print(f"\n📋 {name}:")
    if null_df.empty:
        print("   ✅ No null values")
    else:
        print(null_df.to_string())

# Rating NaN is expected (only rated items have ratings)
interact["Rating"].fillna(0, inplace=True)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 5 — STEP 2: Display DataFrames
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
print(f"\n{'━'*55}")
print("  STEP 2 — DATASET OVERVIEW")
print(f"{'━'*55}")

print("\n👤 USERS — first 5 rows:")
display(users.head())
print("\n📦 PRODUCTS — first 5 rows:")
display(products.head())
print("\n🔁 INTERACTIONS — first 5 rows:")
display(interact.head())

print("\n📊 Users — Statistics:"); display(users.describe(include="all").T)
print("\n📊 Products — Statistics:"); display(products.describe(include="all").T)
print("\n📊 Interactions — Statistics:"); display(interact.describe(include="all").T)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 6 — STEP 3: Visualisations (10 Charts)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
print(f"\n{'━'*55}")
print("  STEP 3 — DATA VISUALISATIONS")
print(f"{'━'*55}")

# ── Chart 1: User Age Distribution + Gender Split ────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("User Demographics", fontsize=16, fontweight="bold")

axes[0].hist(users["Age"], bins=20, color=P[0], edgecolor="white", alpha=0.9)
axes[0].set_xlabel("Age"); axes[0].set_ylabel("Count")
axes[0].set_title("User Age Distribution")
axes[0].axvline(users["Age"].mean(), color=P[2], linestyle="--",
                linewidth=2, label=f"Mean: {users['Age'].mean():.0f}")
axes[0].legend()

gender_c = users["Gender"].value_counts()
wedge_props = {"edgecolor": "white", "linewidth": 2}
axes[1].pie(gender_c.values, labels=gender_c.index,
            colors=P[:len(gender_c)], autopct="%1.1f%%",
            startangle=90, wedgeprops=wedge_props)
axes[1].set_title("Gender Distribution")
plt.tight_layout(); plt.savefig("01_user_demographics.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 01_user_demographics.png")

# ── Chart 2: Products by Category ───────────────────────────
cat_count  = products["Category"].value_counts()
cat_revenue= products.groupby("Category")["Final_Price"].mean()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Product Catalogue Overview", fontsize=16, fontweight="bold")

bars = axes[0].barh(cat_count.index, cat_count.values,
                    color=P[:len(cat_count)], edgecolor="white")
axes[0].set_xlabel("Number of Products"); axes[0].set_title("Products per Category")
for bar, val in zip(bars, cat_count.values):
    axes[0].text(val + 0.1, bar.get_y() + bar.get_height()/2,
                 str(val), va="center", fontsize=10)

bars2 = axes[1].bar(cat_revenue.index, cat_revenue.values,
                    color=P[:len(cat_revenue)], edgecolor="white", width=0.6)
axes[1].set_ylabel("Avg Price (₹)"); axes[1].set_title("Avg Price per Category")
axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(
    lambda x, _: f"₹{x/1e3:.0f}K"))
axes[1].tick_params(axis="x", rotation=30)
for bar, val in zip(bars2, cat_revenue.values):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 50,
                 f"₹{val/1e3:.1f}K", ha="center", fontsize=8)
plt.tight_layout(); plt.savefig("02_product_overview.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 02_product_overview.png")

# ── Chart 3: Interaction Types & Devices ─────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("User Behaviour Analysis", fontsize=16, fontweight="bold")

action_c = interact["Action"].value_counts()
axes[0].bar(action_c.index, action_c.values,
            color=P[:len(action_c)], edgecolor="white", width=0.55)
axes[0].set_ylabel("Count"); axes[0].set_title("Interactions by Action Type")
for bar, val in zip(axes[0].patches, action_c.values):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 20,
                 f"{val:,}", ha="center", fontsize=9)

device_c = interact["Device"].value_counts()
axes[1].pie(device_c.values, labels=device_c.index,
            colors=P[3:3+len(device_c)], autopct="%1.1f%%",
            startangle=90, wedgeprops={"edgecolor":"white","linewidth":2})
axes[1].set_title("Interactions by Device")
plt.tight_layout(); plt.savefig("03_user_behaviour.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 03_user_behaviour.png")

# ── Chart 4: Rating Distribution ─────────────────────────────
rated = interact[interact["Rating"] > 0]
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Rating Analysis", fontsize=16, fontweight="bold")

axes[0].hist(rated["Rating"], bins=20, color=P[1], edgecolor="white", alpha=0.9)
axes[0].set_xlabel("Rating"); axes[0].set_ylabel("Count")
axes[0].set_title("Distribution of User Ratings")
axes[0].axvline(rated["Rating"].mean(), color=P[2], linestyle="--",
                linewidth=2, label=f"Mean: {rated['Rating'].mean():.2f}")
axes[0].legend()

cat_rating = (interact.merge(products[["Product_ID","Category"]], on="Product_ID")
              .groupby("Category")["Rating"]
              .mean().sort_values())
cat_rating = cat_rating[cat_rating > 0]
axes[1].barh(cat_rating.index, cat_rating.values,
             color=P[:len(cat_rating)], edgecolor="white")
axes[1].set_xlabel("Avg Rating"); axes[1].set_title("Avg Rating per Category")
axes[1].set_xlim(0, 5.5)
for bar, val in zip(axes[1].patches, cat_rating.values):
    axes[1].text(val + 0.05, bar.get_y() + bar.get_height()/2,
                 f"{val:.2f}", va="center", fontsize=9)
plt.tight_layout(); plt.savefig("04_rating_analysis.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 04_rating_analysis.png")

# ── Chart 5: Monthly Interaction Trend ───────────────────────
interact["Month"] = interact["Date"].dt.to_period("M")
monthly = interact.groupby("Month").agg(
    Total=("Interaction_ID","count"),
    Purchases=("Purchased","sum")).reset_index()
monthly["Month"] = monthly["Month"].dt.to_timestamp()

fig, ax1 = plt.subplots(figsize=(14, 5))
ax2 = ax1.twinx()
ax1.fill_between(monthly["Month"], monthly["Total"], alpha=0.2, color=P[0])
ax1.plot(monthly["Month"], monthly["Total"], color=P[0], linewidth=2.5,
         marker="o", markersize=4, label="Total Interactions")
ax2.plot(monthly["Month"], monthly["Purchases"], color=P[2], linewidth=2.5,
         marker="s", markersize=5, linestyle="--", label="Purchases")
ax1.set_ylabel("Total Interactions", color=P[0])
ax2.set_ylabel("Purchases", color=P[2])
ax1.set_title("Monthly Interaction & Purchase Trend", fontsize=14, fontweight="bold")
ax1.tick_params(axis="x", rotation=45)
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1+lines2, labels1+labels2, loc="upper left")
ax1.grid(axis="y", linestyle="--", alpha=0.4)
plt.tight_layout(); plt.savefig("05_monthly_trend.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 05_monthly_trend.png")

# ── Chart 6: Top 10 Most Interacted Products ─────────────────
top_prod = (interact.groupby("Product_ID")["Interaction_ID"]
            .count().nlargest(10).reset_index())
top_prod = top_prod.merge(products[["Product_ID","Product_Name","Category"]], on="Product_ID")
top_prod = top_prod.sort_values("Interaction_ID")

colors_top = [P[i % len(P)] for i in range(len(top_prod))]
fig, ax = plt.subplots(figsize=(12, 6))
bars = ax.barh(top_prod["Product_Name"], top_prod["Interaction_ID"],
               color=colors_top, edgecolor="white")
ax.set_xlabel("Number of Interactions")
ax.set_title("Top 10 Most Interacted Products", fontsize=14, fontweight="bold")
for bar, val in zip(bars, top_prod["Interaction_ID"]):
    ax.text(val + 2, bar.get_y() + bar.get_height()/2,
            str(val), va="center", fontsize=9)
plt.tight_layout(); plt.savefig("06_top_products.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 06_top_products.png")

# ── Chart 7: Membership vs Purchase Rate ─────────────────────
merged_u = interact.merge(users[["User_ID","Membership","Age"]], on="User_ID")
mem_stats = merged_u.groupby("Membership").agg(
    Total=("Interaction_ID","count"),
    Purchases=("Purchased","sum")).reset_index()
mem_stats["Purchase_Rate"] = (mem_stats["Purchases"] / mem_stats["Total"] * 100).round(1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Membership Analysis", fontsize=16, fontweight="bold")
axes[0].bar(mem_stats["Membership"], mem_stats["Total"],
            color=P[:3], edgecolor="white", width=0.5, label="Total Interactions")
axes[0].bar(mem_stats["Membership"], mem_stats["Purchases"],
            color=[P[i+3] for i in range(3)], edgecolor="white", width=0.5, label="Purchases")
axes[0].set_title("Interactions vs Purchases by Membership"); axes[0].legend()

axes[1].bar(mem_stats["Membership"], mem_stats["Purchase_Rate"],
            color=P[6:9], edgecolor="white", width=0.5)
axes[1].set_ylabel("Purchase Rate (%)"); axes[1].set_title("Purchase Rate by Membership")
for bar, val in zip(axes[1].patches, mem_stats["Purchase_Rate"]):
    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2,
                 f"{val}%", ha="center", fontsize=10, fontweight="bold")
plt.tight_layout(); plt.savefig("07_membership_analysis.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 07_membership_analysis.png")

# ── Chart 8: Discount vs Rating Scatter ──────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Price & Discount Insights", fontsize=16, fontweight="bold")

for i, cat in enumerate(products["Category"].unique()):
    sub = products[products["Category"]==cat]
    axes[0].scatter(sub["Discount_%"] - sub["Discount_%"]*0.0000000001, sub["Rating_Avg"],
                    label=cat, alpha=0.6, s=50, color=P[i % len(P)])
axes[0].set_xlabel("Discount (%)"); axes[0].set_ylabel("Avg Rating")
axes[0].set_title("Discount vs Rating (by Category)")
axes[0].legend(fontsize=7, ncol=2)

products["Price_Bucket"] = pd.cut(products["Final_Price"],
    bins=[0,500,2000,10000,50000,200000],
    labels=["<500","500-2K","2K-10K","10K-50K","50K+"])
pb_rating = products.groupby("Price_Bucket")["Rating_Avg"].mean()
axes[1].bar(pb_rating.index, pb_rating.values,
            color=P[:len(pb_rating)], edgecolor="white", width=0.6)
axes[1].set_ylabel("Avg Rating"); axes[1].set_xlabel("Price Range (₹)")
axes[1].set_title("Avg Rating by Price Bucket")
axes[1].set_ylim(0, 5.5)
for bar, val in zip(axes[1].patches, pb_rating.values):
    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.05,
                 f"{val:.2f}", ha="center", fontsize=9)
plt.tight_layout(); plt.savefig("08_price_discount_insights.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 08_price_discount_insights.png")

# ── Chart 9: User-Product Interaction Heatmap (top 15) ──────
top15_users = interact["User_ID"].value_counts().head(15).index
top15_prods = interact["Product_ID"].value_counts().head(15).index
heat_df = (interact[interact["User_ID"].isin(top15_users) &
                    interact["Product_ID"].isin(top15_prods)]
           .groupby(["User_ID","Product_ID"])["Rating"].mean().unstack(fill_value=0))

fig, ax = plt.subplots(figsize=(14, 6))
sns.heatmap(heat_df, cmap="YlOrRd", ax=ax, linewidths=0.3,
            cbar_kws={"label":"Avg Rating"}, annot=True, fmt=".1f",
            annot_kws={"size":7})
ax.set_title("User–Product Rating Heatmap (Top 15 Active Users × Top 15 Products)",
             fontsize=13, fontweight="bold")
ax.set_xlabel("Product ID"); ax.set_ylabel("User ID")
plt.tight_layout(); plt.savefig("09_interaction_heatmap.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 09_interaction_heatmap.png")

# ── Chart 10: Category Correlation (user purchase patterns) ──
user_cat = (interact[interact["Purchased"]==1]
            .merge(products[["Product_ID","Category"]], on="Product_ID")
            .groupby(["User_ID","Category"])["Purchased"].sum()
            .unstack(fill_value=0))
corr_cat = user_cat.corr()

fig, ax = plt.subplots(figsize=(10, 7))
mask = np.triu(np.ones_like(corr_cat, dtype=bool))
sns.heatmap(corr_cat, mask=mask, annot=True, fmt=".2f",
            cmap="coolwarm", center=0, linewidths=0.5, ax=ax,
            cbar_kws={"shrink": 0.8})
ax.set_title("Category Co-Purchase Correlation", fontsize=14, fontweight="bold")
plt.tight_layout(); plt.savefig("10_category_correlation.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 10_category_correlation.png")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 7 — STEP 4: Build Recommendation Engines
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
print(f"\n{'━'*55}")
print("  STEP 4 — RECOMMENDATION ENGINES")
print(f"{'━'*55}")

# ── 4A: Content-Based Filtering ──────────────────────────────
print("\n📌 ENGINE 1: Content-Based Filtering")
print("   Uses product features (category, brand, price, rating)")

le_cat   = LabelEncoder()
le_brand = LabelEncoder()
scaler   = MinMaxScaler()

prod_feat = products.copy()
prod_feat["Category_enc"]    = le_cat.fit_transform(prod_feat["Category"])
prod_feat["Brand_enc"]       = le_brand.fit_transform(prod_feat["Brand"])
prod_feat["Sub_Cat_enc"]     = LabelEncoder().fit_transform(prod_feat["Sub_Category"])

feat_cols = ["Category_enc","Brand_enc","Sub_Cat_enc",
             "Final_Price","Rating_Avg","Discount_%","Review_Count"]
feat_matrix = scaler.fit_transform(prod_feat[feat_cols].fillna(0))
content_sim  = cosine_similarity(feat_matrix)
content_sim_df = pd.DataFrame(content_sim,
                               index=products["Product_ID"],
                               columns=products["Product_ID"])

def content_based_recommend(product_id, n=5):
    """Return top-N similar products based on product features."""
    if product_id not in content_sim_df.index:
        return pd.DataFrame()
    sim_scores = content_sim_df[product_id].drop(product_id).sort_values(ascending=False)
    top_ids    = sim_scores.head(n).index.tolist()
    result     = products[products["Product_ID"].isin(top_ids)].copy()
    result["Similarity_Score"] = result["Product_ID"].map(sim_scores)
    return result[["Product_ID","Product_Name","Category","Brand",
                   "Final_Price","Rating_Avg","Similarity_Score"]].sort_values(
                   "Similarity_Score", ascending=False)

# Test
sample_pid = products["Product_ID"].iloc[0]
print(f"\n   Demo — Products similar to {sample_pid} ({products[products['Product_ID']==sample_pid]['Product_Name'].values[0]}):")
display(content_based_recommend(sample_pid, n=5))
print("   ✅  Content-Based engine ready!")

# ── 4B: Collaborative Filtering (User-User) ──────────────────
print("\n📌 ENGINE 2: Collaborative Filtering (User-User Similarity)")
print("   Uses user rating patterns to find similar users")

rated_interact = interact[interact["Rating"] > 0].copy()
user_item = rated_interact.pivot_table(
    index="User_ID", columns="Product_ID",
    values="Rating", aggfunc="mean").fillna(0)

user_sim = cosine_similarity(user_item)
user_sim_df = pd.DataFrame(user_sim,
                            index=user_item.index,
                            columns=user_item.index)

def collab_recommend(user_id, n=5):
    """Return top-N products based on similar users' ratings."""
    if user_id not in user_sim_df.index:
        return pd.DataFrame()
    sim_users   = user_sim_df[user_id].drop(user_id).sort_values(ascending=False).head(10)
    similar_uids = sim_users.index.tolist()
    # Products rated highly by similar users but not yet seen by this user
    seen = set(user_item.loc[user_id][user_item.loc[user_id] > 0].index)
    scores = {}
    for su in similar_uids:
        if su not in user_item.index: continue
        sim_score = sim_users[su]
        for pid in user_item.columns:
            if pid in seen: continue
            rating = user_item.loc[su, pid]
            if rating > 0:
                scores[pid] = scores.get(pid, 0) + sim_score * rating
    if not scores: return pd.DataFrame()
    top_pids = sorted(scores, key=scores.get, reverse=True)[:n]
    result = products[products["Product_ID"].isin(top_pids)].copy()
    result["Predicted_Score"] = result["Product_ID"].map(scores)
    return result[["Product_ID","Product_Name","Category","Brand",
                   "Final_Price","Rating_Avg","Predicted_Score"]].sort_values(
                   "Predicted_Score", ascending=False)

# Test
sample_uid = user_item.index[0]
print(f"\n   Demo — Recommendations for {sample_uid}:")
display(collab_recommend(sample_uid, n=5))
print("   ✅  Collaborative Filtering engine ready!")

# ── 4C: SVD-Based Matrix Factorisation ───────────────────────
print("\n📌 ENGINE 3: SVD Matrix Factorisation (Latent Factor Model)")
print("   Decomposes the user-item matrix into latent features")

sparse_matrix = csr_matrix(user_item.values)
svd = TruncatedSVD(n_components=20, random_state=42)
user_factors = svd.fit_transform(sparse_matrix)
item_factors = svd.components_.T
predicted_ratings = np.dot(user_factors, svd.components_)
pred_df = pd.DataFrame(predicted_ratings,
                        index=user_item.index,
                        columns=user_item.columns)

# Evaluate SVD (RMSE on known ratings)
known = rated_interact[["User_ID","Product_ID","Rating"]].copy()
known = known[known["User_ID"].isin(pred_df.index) &
              known["Product_ID"].isin(pred_df.columns)]
known["Pred"] = known.apply(
    lambda r: pred_df.loc[r["User_ID"], r["Product_ID"]], axis=1)
rmse = np.sqrt(mean_squared_error(known["Rating"], known["Pred"]))
print(f"\n   📊 SVD Model Evaluation:")
print(f"   RMSE on known ratings : {rmse:.4f}")
print(f"   Explained variance    : {svd.explained_variance_ratio_.sum():.4f}")
print(f"   Latent factors used   : 20")

def svd_recommend(user_id, n=5):
    """Return top-N products using SVD predicted ratings."""
    if user_id not in pred_df.index:
        return pd.DataFrame()
    seen    = set(user_item.loc[user_id][user_item.loc[user_id] > 0].index)
    scores  = pred_df.loc[user_id].drop(list(seen), errors="ignore")
    top_pids = scores.nlargest(n).index.tolist()
    result  = products[products["Product_ID"].isin(top_pids)].copy()
    result["SVD_Score"] = result["Product_ID"].map(scores)
    return result[["Product_ID","Product_Name","Category","Brand",
                   "Final_Price","Rating_Avg","SVD_Score"]].sort_values(
                   "SVD_Score", ascending=False)

print(f"\n   Demo — SVD recommendations for {sample_uid}:")
display(svd_recommend(sample_uid, n=5))
print("   ✅  SVD engine ready!")

# ── 4D: Hybrid Recommender ───────────────────────────────────
print("\n📌 ENGINE 4: Hybrid Recommender (Collaborative + Content)")
print("   Weighted blend of collaborative and content signals")

def hybrid_recommend(user_id, n=5, collab_weight=0.6, content_weight=0.4):
    """
    Blend Collaborative Filtering + Content-Based signals.
    Uses the user's purchase history to anchor content similarity.
    """
    # Collaborative scores
    collab = collab_recommend(user_id, n=n*3)
    if collab.empty: return pd.DataFrame()
    collab_scores = dict(zip(collab["Product_ID"],
                             collab["Predicted_Score"] / (collab["Predicted_Score"].max() + 1e-9)))
    # Content: find most purchased product by user, get similar
    purchased = interact[(interact["User_ID"]==user_id) &
                         (interact["Purchased"]==1)]["Product_ID"].values
    content_scores = {}
    if len(purchased) > 0:
        for pid in purchased[:3]:
            if pid not in content_sim_df.index: continue
            sims = content_sim_df[pid].drop(pid, errors="ignore")
            for k, v in sims.head(n*3).items():
                content_scores[k] = content_scores.get(k, 0) + v
        max_c = max(content_scores.values()) + 1e-9
        content_scores = {k: v/max_c for k, v in content_scores.items()}
    # Blend
    all_pids = set(collab_scores) | set(content_scores)
    seen = set(interact[interact["User_ID"]==user_id]["Product_ID"])
    hybrid = {}
    for pid in all_pids:
        if pid in seen: continue
        c1 = collab_scores.get(pid, 0)
        c2 = content_scores.get(pid, 0)
        hybrid[pid] = collab_weight * c1 + content_weight * c2
    if not hybrid: return pd.DataFrame()
    top_pids = sorted(hybrid, key=hybrid.get, reverse=True)[:n]
    result = products[products["Product_ID"].isin(top_pids)].copy()
    result["Hybrid_Score"] = result["Product_ID"].map(hybrid)
    return result[["Product_ID","Product_Name","Category","Brand",
                   "Final_Price","Rating_Avg","Hybrid_Score"]].sort_values(
                   "Hybrid_Score", ascending=False)

print(f"\n   Demo — Hybrid recommendations for {sample_uid}:")
display(hybrid_recommend(sample_uid, n=5))
print("   ✅  Hybrid engine ready!")

# ── Summary Table ─────────────────────────────────────────────
print(f"\n{'━'*55}")
print("  📊 RECOMMENDATION ENGINES SUMMARY")
print(f"{'━'*55}")
engine_summary = pd.DataFrame({
    "Engine":       ["Content-Based","Collaborative","SVD","Hybrid"],
    "Input":        ["Product features","User ratings","User-Item matrix","Both"],
    "Technique":    ["Cosine Similarity","User-User CF","Matrix Factorisation","Weighted Blend"],
    "Cold Start":   ["Product OK","❌ Needs history","❌ Needs history","Partial OK"],
    "Best For":     ["New users","Existing users","Large datasets","Best accuracy"],
})
display(engine_summary)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 8 — STEP 5: Analytics Insights
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
print(f"\n{'━'*55}")
print("  STEP 5 — KEY BUSINESS ANALYTICS INSIGHTS")
print(f"{'━'*55}")

# Chart 11: SVD Evaluation Plot + Latent Space ────────────────
explained = np.cumsum(svd.explained_variance_ratio_)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("SVD Model Evaluation", fontsize=16, fontweight="bold")
axes[0].plot(range(1, len(explained)+1), explained, marker="o", color=P[0], linewidth=2.5)
axes[0].fill_between(range(1, len(explained)+1), explained, alpha=0.15, color=P[0])
axes[0].axhline(0.8, color=P[2], linestyle="--", label="80% threshold")
axes[0].set_xlabel("Number of Components"); axes[0].set_ylabel("Cumulative Explained Variance")
axes[0].set_title("SVD Explained Variance")
axes[0].legend(); axes[0].grid(axis="y", linestyle="--", alpha=0.4)

axes[1].scatter(user_factors[:, 0], user_factors[:, 1],
                alpha=0.4, s=15, color=P[3])
axes[1].set_xlabel("Latent Factor 1"); axes[1].set_ylabel("Latent Factor 2")
axes[1].set_title("User Embedding in Latent Space")
axes[1].grid(linestyle="--", alpha=0.3)
plt.tight_layout(); plt.savefig("11_svd_evaluation.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 11_svd_evaluation.png")

# Chart 12: Recommendation Comparison for a User ─────────────
uid_demo = sample_uid
def get_rec_names(df, col):
    if df.empty: return []
    return df["Product_Name"].head(5).tolist()

rec_compare = pd.DataFrame({
    "Rank":          [1,2,3,4,5],
    "Content-Based": get_rec_names(content_based_recommend(
        interact[interact["User_ID"]==uid_demo]["Product_ID"].iloc[0], 5), ""),
    "Collaborative": get_rec_names(collab_recommend(uid_demo, 5), ""),
    "SVD":           get_rec_names(svd_recommend(uid_demo, 5), ""),
    "Hybrid":        get_rec_names(hybrid_recommend(uid_demo, 5), ""),
})
print(f"\n🔮 Recommendation comparison for user {uid_demo}:")
display(rec_compare)

# Chart 13: Purchase funnel by Category ───────────────────────
funnel = (interact.merge(products[["Product_ID","Category"]], on="Product_ID")
          .groupby(["Category","Action"])["Interaction_ID"].count()
          .unstack(fill_value=0).reset_index())
funnel_melt = funnel.melt(id_vars="Category", var_name="Action", value_name="Count")

fig, ax = plt.subplots(figsize=(12, 6))
pivot_funnel = funnel_melt.pivot(index="Category", columns="Action", values="Count")
pivot_funnel.plot(kind="bar", ax=ax, color=P[:4], edgecolor="white", width=0.7)
ax.set_title("Purchase Funnel by Category", fontsize=14, fontweight="bold")
ax.set_ylabel("Interactions"); ax.tick_params(axis="x", rotation=30)
ax.legend(title="Action", bbox_to_anchor=(1.01, 1))
plt.tight_layout(); plt.savefig("12_purchase_funnel.png", dpi=150, bbox_inches="tight")
plt.show(); print("✅  Saved: 12_purchase_funnel.png")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 9 — Download all charts
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
charts = ["01_user_demographics","02_product_overview","03_user_behaviour",
          "04_rating_analysis","05_monthly_trend","06_top_products",
          "07_membership_analysis","08_price_discount_insights",
          "09_interaction_heatmap","10_category_correlation",
          "11_svd_evaluation","12_purchase_funnel"]
for c in charts:
    try: files.download(f"{c}.png")
    except: pass

print("✅  All charts downloaded!")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 10 — Write Streamlit App
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
APP = '''
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
import warnings
warnings.filterwarnings("ignore")

st.set_page_config(page_title="AI Product Recommender",
                   page_icon="🤖", layout="wide")

P = ["#5e60ce","#48cae4","#f72585","#06d6a0","#ffd166",
     "#ef476f","#3a86ff","#fb8500","#8ecae6","#95d5b2"]

st.markdown("""
<style>
[data-testid="stMetricValue"]{font-size:1.7rem;font-weight:700;}
.block-container{padding-top:1.5rem;}
.rec-card{background:#f0f4ff;border-radius:10px;padding:12px 16px;
          margin-bottom:8px;border-left:4px solid #5e60ce;}
</style>""", unsafe_allow_html=True)

st.title("🤖 AI-Based Product Recommendation & Analytics System")
st.caption("Content-Based · Collaborative Filtering · SVD · Hybrid Engine")

with st.sidebar:
    st.header("📁 Upload Dataset")
    uploaded = st.file_uploader("Upload Excel File", type=["xlsx"])
    st.divider()
    st.header("🎯 Get Recommendations")
    engine_choice = st.selectbox("Recommendation Engine",
        ["Hybrid (Best)","Collaborative Filtering","Content-Based","SVD"])
    n_recs = st.slider("Number of Recommendations", 3, 10, 5)
    st.divider()
    st.header("🔍 Filters")
    max_price = st.slider("Max Price (₹)", 100, 100000, 50000, step=500)

@st.cache_data
def load_all(file):
    users    = pd.read_excel(file, sheet_name="Users",        parse_dates=["Join_Date"])
    products = pd.read_excel(file, sheet_name="Products",     parse_dates=["Launch_Date"])
    interact = pd.read_excel(file, sheet_name="Interactions", parse_dates=["Date"])
    interact["Rating"].fillna(0, inplace=True)
    return users, products, interact

@st.cache_resource
def build_engines(_products, _interact):
    # Content-Based
    pf = _products.copy()
    pf["Category_enc"] = LabelEncoder().fit_transform(pf["Category"])
    pf["Brand_enc"]    = LabelEncoder().fit_transform(pf["Brand"])
    pf["SubCat_enc"]   = LabelEncoder().fit_transform(pf["Sub_Category"])
    feat = MinMaxScaler().fit_transform(
        pf[["Category_enc","Brand_enc","SubCat_enc",
            "Final_Price","Rating_Avg","Discount_%","Review_Count"]].fillna(0))
    csim = pd.DataFrame(cosine_similarity(feat),
                        index=_products["Product_ID"],
                        columns=_products["Product_ID"])
    # Collaborative
    rated = _interact[_interact["Rating"]>0]
    ui = rated.pivot_table(index="User_ID", columns="Product_ID",
                           values="Rating", aggfunc="mean").fillna(0)
    usim = pd.DataFrame(cosine_similarity(ui), index=ui.index, columns=ui.index)
    # SVD
    svd = TruncatedSVD(n_components=20, random_state=42)
    uf  = svd.fit_transform(csr_matrix(ui.values))
    pred= pd.DataFrame(np.dot(uf, svd.components_),
                       index=ui.index, columns=ui.columns)
    return csim, usim, ui, pred

if uploaded is None:
    st.info("👈 Upload **Product_Recommendation_Dataset.xlsx** to begin.")
    st.stop()

users, products, interact = load_all(uploaded)
csim, usim, ui, pred_df   = build_engines(products, interact)

# ── KPI Row ──────────────────────────────────────────────────
total_rev = (interact[interact["Purchased"]==1]
             .merge(products[["Product_ID","Final_Price"]], on="Product_ID")["Final_Price"].sum())
k1,k2,k3,k4,k5 = st.columns(5)
k1.metric("Total Users",     f"{len(users):,}")
k2.metric("Total Products",  f"{len(products):,}")
k3.metric("Total Interactions", f"{len(interact):,}")
k4.metric("Total Purchases", f"{interact['Purchased'].sum():,}")
k5.metric("Est. Revenue",    f"₹{total_rev/1e6:.1f}M")

st.divider()

tab_reco, tab_analytics, tab_products, tab_users, tab_insights = st.tabs([
    "🎯 Recommendations","📊 Analytics","📦 Products","👤 Users","🔬 Model Insights"])

# ── HELPER FUNCTIONS ────────────────────────────────────────
def content_rec(pid, n):
    if pid not in csim.index: return pd.DataFrame()
    sims = csim[pid].drop(pid).sort_values(ascending=False)
    top  = sims.head(n).index
    r    = products[products["Product_ID"].isin(top)].copy()
    r["Score"] = r["Product_ID"].map(sims)
    return r[r["Final_Price"]<=max_price].sort_values("Score",ascending=False)

def collab_rec(uid, n):
    if uid not in usim.index: return pd.DataFrame()
    sim_u = usim[uid].drop(uid).sort_values(ascending=False).head(10)
    seen  = set(ui.loc[uid][ui.loc[uid]>0].index)
    scores={}
    for su in sim_u.index:
        for pid in ui.columns:
            if pid in seen: continue
            rat = ui.loc[su,pid]
            if rat>0: scores[pid]=scores.get(pid,0)+sim_u[su]*rat
    if not scores: return pd.DataFrame()
    top = sorted(scores,key=scores.get,reverse=True)[:n]
    r   = products[products["Product_ID"].isin(top)].copy()
    r["Score"] = r["Product_ID"].map(scores)
    return r[r["Final_Price"]<=max_price].sort_values("Score",ascending=False)

def svd_rec(uid, n):
    if uid not in pred_df.index: return pd.DataFrame()
    seen  = set(ui.loc[uid][ui.loc[uid]>0].index)
    scores= pred_df.loc[uid].drop(list(seen),errors="ignore")
    top   = scores.nlargest(n).index
    r     = products[products["Product_ID"].isin(top)].copy()
    r["Score"] = r["Product_ID"].map(scores)
    return r[r["Final_Price"]<=max_price].sort_values("Score",ascending=False)

def hybrid_rec(uid, n):
    c1 = collab_rec(uid, n*3)
    if c1.empty: return pd.DataFrame()
    cs = dict(zip(c1["Product_ID"], c1["Score"]/(c1["Score"].max()+1e-9)))
    purchased = interact[(interact["User_ID"]==uid)&(interact["Purchased"]==1)]["Product_ID"].values
    ct={}
    if len(purchased)>0:
        for pid in purchased[:3]:
            if pid not in csim.index: continue
            for k,v in csim[pid].drop(pid,errors="ignore").head(n*2).items():
                ct[k]=ct.get(k,0)+v
        maxc=max(ct.values())+1e-9
        ct={k:v/maxc for k,v in ct.items()}
    seen=set(interact[interact["User_ID"]==uid]["Product_ID"])
    hyb={p:0.6*cs.get(p,0)+0.4*ct.get(p,0) for p in set(cs)|set(ct) if p not in seen}
    if not hyb: return pd.DataFrame()
    top=sorted(hyb,key=hyb.get,reverse=True)[:n]
    r=products[products["Product_ID"].isin(top)].copy()
    r["Score"]=r["Product_ID"].map(hyb)
    return r[r["Final_Price"]<=max_price].sort_values("Score",ascending=False)

# ── TAB 1: RECOMMENDATIONS ───────────────────────────────────
with tab_reco:
    st.subheader("🎯 Personalised Recommendations")
    r_col1, r_col2 = st.columns([1, 1])
    with r_col1:
        st.markdown("#### For a User")
        uid_sel = st.selectbox("Select User", sorted(users["User_ID"].tolist()), key="uid_reco")
        if st.button("Get User Recommendations", use_container_width=True):
            if   engine_choice.startswith("Hybrid"):     rdf = hybrid_rec(uid_sel, n_recs)
            elif engine_choice.startswith("Collab"):     rdf = collab_rec(uid_sel, n_recs)
            elif engine_choice.startswith("SVD"):        rdf = svd_rec(uid_sel, n_recs)
            else:
                hist = interact[interact["User_ID"]==uid_sel]["Product_ID"]
                rdf  = content_rec(hist.iloc[0], n_recs) if len(hist)>0 else pd.DataFrame()
            if rdf.empty:
                st.warning("Not enough interaction history for this user.")
            else:
                u_info = users[users["User_ID"]==uid_sel].iloc[0]
                st.info(f"👤 {uid_sel} | Age {u_info['Age']} | {u_info['Location']} | {u_info['Membership']}")
                for _, row in rdf.iterrows():
                    disc = f"  🏷️ {int(row.get('Discount_%',0))}% off" if row.get("Discount_%",0)>0 else ""
                    st.markdown(f"""<div class="rec-card">
                    <b>{row["Product_Name"]}</b> — {row["Category"]}<br>
                    ₹{row["Final_Price"]:,.0f}{disc} &nbsp;|&nbsp; ⭐ {row["Rating_Avg"]}
                    </div>""", unsafe_allow_html=True)
    with r_col2:
        st.markdown("#### For a Product (Similar Items)")
        pid_sel = st.selectbox("Select Product",
            products["Product_ID"].tolist(),
            format_func=lambda x: f"{x} — {products[products['Product_ID']==x]['Product_Name'].values[0]}",
            key="pid_reco")
        if st.button("Get Similar Products", use_container_width=True):
            sdf = content_rec(pid_sel, n_recs)
            if sdf.empty:
                st.warning("No similar products found.")
            else:
                p_info = products[products["Product_ID"]==pid_sel].iloc[0]
                st.info(f"📦 {p_info['Product_Name']} | {p_info['Category']} | ₹{p_info['Final_Price']:,}")
                for _, row in sdf.iterrows():
                    disc = f"  🏷️ {int(row.get('Discount_%',0))}% off" if row.get("Discount_%",0)>0 else ""
                    st.markdown(f"""<div class="rec-card">
                    <b>{row["Product_Name"]}</b> — {row["Category"]}<br>
                    ₹{row["Final_Price"]:,.0f}{disc} &nbsp;|&nbsp; ⭐ {row["Rating_Avg"]}
                    </div>""", unsafe_allow_html=True)

# ── TAB 2: ANALYTICS ─────────────────────────────────────────
with tab_analytics:
    st.subheader("📊 Platform Analytics")
    ac1, ac2 = st.columns(2)
    with ac1:
        monthly = interact.copy()
        monthly["Month"] = monthly["Date"].dt.to_period("M")
        mon = monthly.groupby("Month").agg(
            Total=("Interaction_ID","count"),
            Purchases=("Purchased","sum")).reset_index()
        mon["Month"] = mon["Month"].dt.to_timestamp()
        fig,ax = plt.subplots(figsize=(7,4))
        ax.fill_between(mon["Month"], mon["Total"], alpha=0.2, color=P[0])
        ax.plot(mon["Month"], mon["Total"], color=P[0], linewidth=2, marker="o", markersize=3)
        ax.set_title("Monthly Interactions"); ax.tick_params(axis="x",rotation=45)
        ax.grid(axis="y",linestyle="--",alpha=0.4)
        plt.tight_layout(); st.pyplot(fig); plt.close()
    with ac2:
        action_c = interact["Action"].value_counts()
        fig,ax = plt.subplots(figsize=(7,4))
        ax.bar(action_c.index, action_c.values, color=P[:4], edgecolor="white", width=0.5)
        ax.set_title("Interactions by Action")
        for bar,val in zip(ax.patches, action_c.values):
            ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+10,
                    f"{val:,}", ha="center", fontsize=9)
        plt.tight_layout(); st.pyplot(fig); plt.close()
    ac3, ac4 = st.columns(2)
    with ac3:
        cat_pur = (interact[interact["Purchased"]==1]
                   .merge(products[["Product_ID","Category"]],"left","Product_ID")
                   .groupby("Category").size().sort_values(ascending=False))
        fig,ax = plt.subplots(figsize=(7,4))
        ax.barh(cat_pur.index, cat_pur.values, color=P[:len(cat_pur)], edgecolor="white")
        ax.set_title("Purchases by Category")
        plt.tight_layout(); st.pyplot(fig); plt.close()
    with ac4:
        rated = interact[interact["Rating"]>0]
        fig,ax = plt.subplots(figsize=(7,4))
        ax.hist(rated["Rating"], bins=20, color=P[1], edgecolor="white", alpha=0.9)
        ax.axvline(rated["Rating"].mean(), color=P[2], linestyle="--", linewidth=2,
                   label=f"Mean: {rated['Rating'].mean():.2f}")
        ax.set_title("Rating Distribution"); ax.legend()
        plt.tight_layout(); st.pyplot(fig); plt.close()

# ── TAB 3: PRODUCTS ──────────────────────────────────────────
with tab_products:
    st.subheader("📦 Product Catalogue")
    cat_filter = st.multiselect("Filter by Category", products["Category"].unique(),
                                default=list(products["Category"].unique()))
    show_prod = products[products["Category"].isin(cat_filter) &
                         (products["Final_Price"]<=max_price)]
    st.dataframe(show_prod[["Product_ID","Product_Name","Category","Brand",
                              "Final_Price","Discount_%","Rating_Avg","Review_Count",
                              "Stock"]].reset_index(drop=True),
                 use_container_width=True)
    c1,c2 = st.columns(2)
    with c1:
        cp = show_prod.groupby("Category")["Final_Price"].mean().sort_values(ascending=False)
        fig,ax = plt.subplots(figsize=(7,4))
        ax.bar(cp.index, cp.values, color=P[:len(cp)], edgecolor="white", width=0.6)
        ax.set_title("Avg Price by Category")
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x,_: f"₹{x/1e3:.0f}K"))
        ax.tick_params(axis="x", rotation=30)
        plt.tight_layout(); st.pyplot(fig); plt.close()
    with c2:
        top10 = show_prod.nlargest(10,"Review_Count")[["Product_Name","Rating_Avg","Review_Count"]]
        fig,ax = plt.subplots(figsize=(7,4))
        ax.barh(top10["Product_Name"], top10["Review_Count"],
                color=P[:10], edgecolor="white")
        ax.set_title("Top 10 Most Reviewed Products")
        plt.tight_layout(); st.pyplot(fig); plt.close()

# ── TAB 4: USERS ─────────────────────────────────────────────
with tab_users:
    st.subheader("👤 User Analysis")
    u1,u2 = st.columns(2)
    with u1:
        fig,ax = plt.subplots(figsize=(7,4))
        ax.hist(users["Age"], bins=20, color=P[0], edgecolor="white", alpha=0.9)
        ax.axvline(users["Age"].mean(), color=P[2], linestyle="--",
                   linewidth=2, label=f"Mean: {users['Age'].mean():.0f}")
        ax.set_title("Age Distribution"); ax.legend()
        plt.tight_layout(); st.pyplot(fig); plt.close()
    with u2:
        loc_c = users["Location"].value_counts()
        fig,ax = plt.subplots(figsize=(7,4))
        ax.bar(loc_c.index, loc_c.values, color=P[:len(loc_c)], edgecolor="white", width=0.6)
        ax.set_title("Users by City"); ax.tick_params(axis="x",rotation=30)
        plt.tight_layout(); st.pyplot(fig); plt.close()
    u3,u4 = st.columns(2)
    with u3:
        mem_c = users["Membership"].value_counts()
        fig,ax = plt.subplots(figsize=(7,4))
        ax.pie(mem_c.values, labels=mem_c.index, colors=P[:3],
               autopct="%1.1f%%", startangle=90,
               wedgeprops={"edgecolor":"white","linewidth":2})
        ax.set_title("Membership Distribution")
        plt.tight_layout(); st.pyplot(fig); plt.close()
    with u4:
        merged = interact.merge(users[["User_ID","Membership"]], on="User_ID")
        mem_pur = merged.groupby("Membership")["Purchased"].mean()*100
        fig,ax = plt.subplots(figsize=(7,4))
        ax.bar(mem_pur.index, mem_pur.values, color=P[3:6], edgecolor="white", width=0.5)
        ax.set_ylabel("Purchase Rate (%)")
        ax.set_title("Purchase Rate by Membership")
        for bar,val in zip(ax.patches, mem_pur.values):
            ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2,
                    f"{val:.1f}%", ha="center", fontsize=10)
        plt.tight_layout(); st.pyplot(fig); plt.close()

# ── TAB 5: MODEL INSIGHTS ─────────────────────────────────────
with tab_insights:
    st.subheader("🔬 Model & Engine Insights")
    engine_summary = pd.DataFrame({
        "Engine":    ["Content-Based","Collaborative","SVD","Hybrid"],
        "Technique": ["Cosine Similarity","User-User CF","Matrix Factorisation","Weighted Blend"],
        "Input":     ["Product features","User ratings","User-Item matrix","Both"],
        "Cold Start":["✅ Product OK","❌ Needs history","❌ Needs history","⚠️ Partial"],
        "Best For":  ["New users","Existing users","Large datasets","Best accuracy"],
    })
    st.dataframe(engine_summary, use_container_width=True, hide_index=True)
    st.markdown("---")
    i1,i2 = st.columns(2)
    with i1:
        svd = TruncatedSVD(n_components=20, random_state=42)
        from scipy.sparse import csr_matrix as csrm
        svd.fit(csrm(ui.values))
        exp_var = np.cumsum(svd.explained_variance_ratio_)
        fig,ax = plt.subplots(figsize=(6,4))
        ax.plot(range(1,len(exp_var)+1), exp_var, marker="o", color=P[0], linewidth=2)
        ax.axhline(0.8, color=P[2], linestyle="--", label="80% threshold")
        ax.set_xlabel("Components"); ax.set_ylabel("Cumulative Variance")
        ax.set_title("SVD Explained Variance"); ax.legend()
        ax.grid(axis="y", linestyle="--", alpha=0.4)
        plt.tight_layout(); st.pyplot(fig); plt.close()
    with i2:
        top15u = interact["User_ID"].value_counts().head(12).index
        top15p = interact["Product_ID"].value_counts().head(12).index
        h = (interact[interact["User_ID"].isin(top15u) &
                      interact["Product_ID"].isin(top15p)]
             .groupby(["User_ID","Product_ID"])["Rating"].mean().unstack(fill_value=0))
        fig,ax = plt.subplots(figsize=(7,5))
        sns.heatmap(h, cmap="YlOrRd", ax=ax, linewidths=0.3,
                    cbar_kws={"label":"Avg Rating"}, annot=True, fmt=".1f",
                    annot_kws={"size":7})
        ax.set_title("User-Product Rating Heatmap")
        plt.tight_layout(); st.pyplot(fig); plt.close()
    st.info(f"📊 SVD RMSE on known ratings: evaluated on {len(interact[interact['Rating']>0]):,} rated interactions")
'''

with open("app.py", "w") as f:
    f.write(APP)
print("✅  app.py written!")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CELL 11 — Launch Streamlit App
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
!pip install pyngrok streamlit -q

import subprocess, time
from pyngrok import ngrok, conf

NGROK_TOKEN = "YOUR_NGROK_TOKEN_HERE"   # ← Get free token from dashboard.ngrok.com

conf.get_default().auth_token = NGROK_TOKEN
proc = subprocess.Popen(
    ["streamlit","run","app.py",
     "--server.port","8501",
     "--server.headless","true"],
    stdout=subprocess.PIPE, stderr=subprocess.PIPE
)
time.sleep(5)
public_url = ngrok.connect(8501)
print("="*60)
print(f"  🚀  AI Recommender App is LIVE at:")
print(f"  {public_url}")
print("="*60)

